// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCql90kmlCht7t08yjN8WEJdKYsOFomjzY',
    appId: '1:902850004705:web:49aaca66cc60c3e8b019a0',
    messagingSenderId: '902850004705',
    projectId: 'doitnow-e04d4',
    authDomain: 'doitnow-e04d4.firebaseapp.com',
    storageBucket: 'doitnow-e04d4.appspot.com',
    measurementId: 'G-GBXNXS04KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkT9uMKMPD9R5TRSaIpeQEfRKMs0jUvD4',
    appId: '1:902850004705:android:1fbb6a7c7712c1dcb019a0',
    messagingSenderId: '902850004705',
    projectId: 'doitnow-e04d4',
    storageBucket: 'doitnow-e04d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QNmSmxe8DT21YA2bPCEe7MSkgK1GCdc',
    appId: '1:902850004705:ios:e01bf6e7b2a9c2bdb019a0',
    messagingSenderId: '902850004705',
    projectId: 'doitnow-e04d4',
    storageBucket: 'doitnow-e04d4.appspot.com',
    iosBundleId: 'com.example.doitnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QNmSmxe8DT21YA2bPCEe7MSkgK1GCdc',
    appId: '1:902850004705:ios:c99d7ac7e1efcfd1b019a0',
    messagingSenderId: '902850004705',
    projectId: 'doitnow-e04d4',
    storageBucket: 'doitnow-e04d4.appspot.com',
    iosBundleId: 'com.example.doitnow.RunnerTests',
  );
}
